### ISSUE TITLE
Service Providers Management Page in Franchise

### ISSUE THREAD

**Issue by JaseelaAlimahamed** [JaseelaAlimahamed/ServiceConnectAdminUI#67]
Create a Service Providers Management Page for the Franchise Portal. This page will serve as a central hub for managing service providers associated with the franchise. It should include a table displaying key information about each service provider, along with actions for editing, verifying, and deleting entries.

Sections to Include:

Page Header:

Title: "Service Providers Management"
A brief description or instruction on managing service providers.
Service Providers Table:

Create a responsive table to display the following columns:
Profile Photo: A thumbnail of the provider's profile picture.
Provider Name: The name of the service provider.
Contact Information: Email and phone number.
Verification Status: Indicate if the provider is verified or pending verification.
Service Type: The type of services offered by the provider.
Registration Date: The date when the provider registered with the franchise.
Actions: Buttons/links for actions like:
View Details: Navigate to the provider's details page.
Edit: Edit the provider's information.
Verify: Change the verification status.
Delete: Remove the provider from the list (with confirmation).

Add New Provider Button:

A button at the top of the table to add a new service provider. This should navigate to a form for entering new provider details.

as per the design in figma

**Comment by Mwonuu** [comment]
Completed
